services:
  git:
    image: alpine/git
    volumes:
      - shared:/git
    command: git clone https://github.com/boxfuse/boxfuse-sample-java-war-hello.git /git
  maven:
    image: maven:3.6-alpine
    depends_on:
      git:
        condition: service_completed_successfully
    volumes:
      - shared:/git
      - /war:/war
    command: mvn -f /git/pom.xml package && cp /git/target/*.war /war/
  tomcat:
    image: tomcat:9.0.63-jre8-openjdk-slim-buster
    build: .
    depends_on:
      maven:
        condition: service_completed_successfully
    volumes:
      - shared:/git
    ports:
      - "80:8080"

volumes:
  shared: